#![allow(unused)]
use crossterm::event::{KeyCode, KeyEvent, KeyEventKind, KeyModifiers, MouseButton, MouseEvent, MouseEventKind};
use strum::EnumCount;

#[derive(Copy, Clone, PartialEq, Eq, EnumCount)]
pub enum Key {
    Escape,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    BackTick,
    One,
    Two,
    Three,
    Four,
    Five,
    Six,
    Seven,
    Eight,
    Nine,
    Zero,
    Minus,
    Equal,
    Backspace,
    Tab,
    Q,
    W,
    E,
    R,
    T,
    Y,
    U,
    I,
    O,
    P,
    LeftBracket,
    RightBracket,
    Backslash,
    A,
    S,
    D,
    F,
    G,
    H,
    J,
    K,
    L,
    Semicolon,
    Quote,
    Return,
    Z,
    X,
    C,
    V,
    B,
    N,
    M,
    Comma,
    Dot,
    Slash,
    Space,

    Squiggle,
    Bang,
    At,
    Hash,
    Dollar,
    Percent,
    Caret,
    Ampersand,
    Star,
    LeftParen,
    RightParen,
    Underscore,
    Plus,
    BackTab,
    UpperQ,
    UpperW,
    UpperE,
    UpperR,
    UpperT,
    UpperY,
    UpperU,
    UpperI,
    UpperO,
    UpperP,
    LeftBrace,
    RightBrace,
    Bar,
    UpperA,
    UpperS,
    UpperD,
    UpperF,
    UpperG,
    UpperH,
    UpperJ,
    UpperK,
    UpperL,
    Colon,
    DoubleQuote,
    UpperZ,
    UpperX,
    UpperC,
    UpperV,
    UpperB,
    UpperN,
    UpperM,
    LessThan,
    GreaterThan,
    Question,

    CtrlA,
    CtrlB,
    CtrlC,
    CtrlD,
    CtrlE,
    CtrlF,
    CtrlG,
    CtrlH,
    CtrlJ,
    CtrlK,
    CtrlL,
    CtrlN,
    CtrlO,
    CtrlP,
    CtrlQ,
    CtrlR,
    CtrlS,
    CtrlT,
    CtrlU,
    CtrlV,
    CtrlW,
    CtrlX,
    CtrlY,
    CtrlZ,
    Ctrl4,
    Ctrl5,
    Ctrl6,
    Ctrl7,

    AltEscape,
    AltF1,
    AltF2,
    AltF3,
    AltF4,
    AltF5,
    AltF6,
    AltF7,
    AltF8,
    AltF9,
    AltF10,
    AltF11,
    AltF12,
    AltBackTick,
    AltOne,
    AltTwo,
    AltThree,
    AltFour,
    AltFive,
    AltSix,
    AltSeven,
    AltEight,
    AltNine,
    AltZero,
    AltMinus,
    AltEqual,
    AltBackspace,
    AltTab,
    AltQ,
    AltW,
    AltE,
    AltR,
    AltT,
    AltY,
    AltU,
    AltI,
    AltO,
    AltP,
    AltLeftBracket,
    AltRightBracket,
    AltBackslash,
    AltA,
    AltS,
    AltD,
    AltF,
    AltG,
    AltH,
    AltJ,
    AltK,
    AltL,
    AltSemicolon,
    AltQuote,
    AltReturn,
    AltZ,
    AltX,
    AltC,
    AltV,
    AltB,
    AltN,
    AltM,
    AltComma,
    AltDot,
    AltSlash,
    AltSpace,

    AltSquiggle,
    AltBang,
    AltAt,
    AltHash,
    AltDollar,
    AltPercent,
    AltCaret,
    AltAmpersand,
    AltStar,
    AltLeftParen,
    AltRightParen,
    AltUnderscore,
    AltPlus,
    AltBackTab,
    AltUpperQ,
    AltUpperW,
    AltUpperE,
    AltUpperR,
    AltUpperT,
    AltUpperY,
    AltUpperU,
    AltUpperI,
    AltUpperO,
    AltUpperP,
    AltLeftBrace,
    AltRightBrace,
    AltBar,
    AltUpperA,
    AltUpperS,
    AltUpperD,
    AltUpperF,
    AltUpperG,
    AltUpperH,
    AltUpperJ,
    AltUpperK,
    AltUpperL,
    AltColon,
    AltDoubleQuote,
    AltUpperZ,
    AltUpperX,
    AltUpperC,
    AltUpperV,
    AltUpperB,
    AltUpperN,
    AltUpperM,
    AltLessThan,
    AltGreaterThan,
    AltQuestion,

    CtrlAltA,
    CtrlAltB,
    CtrlAltC,
    CtrlAltD,
    CtrlAltE,
    CtrlAltF,
    CtrlAltG,
    CtrlAltH,
    CtrlAltJ,
    CtrlAltK,
    CtrlAltL,
    CtrlAltN,
    CtrlAltO,
    CtrlAltP,
    CtrlAltQ,
    CtrlAltR,
    CtrlAltS,
    CtrlAltT,
    CtrlAltU,
    CtrlAltV,
    CtrlAltW,
    CtrlAltX,
    CtrlAltY,
    CtrlAltZ,
    CtrlAlt4,
    CtrlAlt5,
    CtrlAlt6,
    CtrlAlt7,

    ScrollUp,
    ScrollDown,
    ScrollLeft,
    ScrollRight,

    LeftClick,
    LeftDrag,

    AltLeftClick,
    AltLeftDrag,
}

#[derive(Copy, Clone, PartialEq, Eq)]
pub enum KeyOrChar {
    Key(Key),
    Char(char),
}

impl From<Key> for KeyOrChar {
    fn from(value: Key) -> Self {
        Self::Key(value)
    }
}

impl KeyOrChar {
    pub fn from_key_event(value: KeyEvent) -> Option<Self> {
        let KeyEvent { code, modifiers, kind, .. } = value;
        if !matches!(kind, KeyEventKind::Press | KeyEventKind::Repeat) {return None};
    
        let alt = modifiers.contains(KeyModifiers::ALT);
        let ctrl = modifiers.contains(KeyModifiers::CONTROL);
    
        macro alt {
            (ctrl $($k:tt)*) => {
                Self::Key(if alt {key!(ctrl alt $($k)*)} else {key!(ctrl $($k)*)})
            },
            ($($k:tt)*) => {
                Self::Key(if alt {key!(alt $($k)*)} else {key!($($k)*)})
            },
        }
    
        Some(match code {
            KeyCode::Backspace => alt![backspace],
            KeyCode::Enter => alt![return],
            KeyCode::Tab => alt![tab],
            KeyCode::BackTab => alt![back tab],
            KeyCode::Esc => alt![esc],
            KeyCode::F(1) => alt![f1],
            KeyCode::F(2) => alt![f2],
            KeyCode::F(3) => alt![f3],
            KeyCode::F(4) => alt![f4],
            KeyCode::F(5) => alt![f5],
            KeyCode::F(6) => alt![f6],
            KeyCode::F(7) => alt![f7],
            KeyCode::F(8) => alt![f8],
            KeyCode::F(9) => alt![f9],
            KeyCode::F(10) => alt![f10],
            KeyCode::F(11) => alt![f11],
            KeyCode::F(12) => alt![f12],
            KeyCode::Char(c) =>
                if !ctrl {match c {
                    '`' => alt!['`'],
                    '1' => alt![1],
                    '2' => alt![2],
                    '3' => alt![3],
                    '4' => alt![4],
                    '5' => alt![5],
                    '6' => alt![6],
                    '7' => alt![7],
                    '8' => alt![8],
                    '9' => alt![9],
                    '0' => alt![0],
                    '-' => alt![-],
                    '=' => alt![=],
                    'q' => alt![q],
                    'w' => alt![w],
                    'e' => alt![e],
                    'r' => alt![r],
                    't' => alt![t],
                    'y' => alt![y],
                    'u' => alt![u],
                    'i' => alt![i],
                    'o' => alt![o],
                    'p' => alt![p],
                    '[' => alt!['['],
                    ']' => alt![']'],
                    '\\' => alt![backslash],
                    'a' => alt![a],
                    's' => alt![s],
                    'd' => alt![d],
                    'f' => alt![f],
                    'g' => alt![g],
                    'h' => alt![h],
                    'j' => alt![j],
                    'k' => alt![k],
                    'l' => alt![l],
                    ';' => alt![;],
                    '\'' => alt!["'"],
                    'z' => alt![z],
                    'x' => alt![x],
                    'c' => alt![c],
                    'v' => alt![v],
                    'b' => alt![b],
                    'n' => alt![n],
                    'm' => alt![m],
                    ',' => alt![,],
                    '.' => alt![.],
                    '/' => alt![/],
                    ' ' => alt![ ],
                    '~' => alt![~],
                    '!' => alt![!],
                    '@' => alt![@],
                    '#' => alt![#],
                    '$' => alt![$],
                    '%' => alt![%],
                    '^' => alt![^],
                    '&' => alt![&],
                    '*' => alt![*],
                    '(' => alt!['('],
                    ')' => alt![')'],
                    '_' => alt![_],
                    '+' => alt![+],
                    'Q' => alt![Q],
                    'W' => alt![W],
                    'E' => alt![E],
                    'R' => alt![R],
                    'T' => alt![T],
                    'Y' => alt![Y],
                    'U' => alt![U],
                    'I' => alt![I],
                    'O' => alt![O],
                    'P' => alt![P],
                    '{' => alt!['{'],
                    '}' => alt!['}'],
                    '|' => alt![|],
                    'A' => alt![A],
                    'S' => alt![S],
                    'D' => alt![D],
                    'F' => alt![F],
                    'G' => alt![G],
                    'H' => alt![H],
                    'J' => alt![J],
                    'K' => alt![K],
                    'L' => alt![L],
                    ':' => alt![:],
                    '"' => alt!['"'],
                    'Z' => alt![Z],
                    'X' => alt![X],
                    'C' => alt![C],
                    'V' => alt![V],
                    'B' => alt![B],
                    'N' => alt![N],
                    'M' => alt![M],
                    '<' => alt![<],
                    '>' => alt![>],
                    '?' => alt![?],
                    c if !alt => Self::Char(c),
                    _ => None::<!>?,
                }} else {match c {    
                    'A' | 'a' => alt![ctrl a],
                    'B' | 'b' => alt![ctrl b],
                    'C' | 'c' => alt![ctrl c],
                    'D' | 'd' => alt![ctrl d],
                    'E' | 'e' => alt![ctrl e],
                    'F' | 'f' => alt![ctrl f],
                    'G' | 'g' => alt![ctrl g],
                    'H' | 'h' => alt![ctrl h],
                    'J' | 'j' => alt![ctrl j],
                    'K' | 'k' => alt![ctrl k],
                    'L' | 'l' => alt![ctrl l],
                    'N' | 'n' => alt![ctrl n],
                    'O' | 'o' => alt![ctrl o],
                    'P' | 'p' => alt![ctrl p],
                    'Q' | 'q' => alt![ctrl q],
                    'R' | 'r' => alt![ctrl r],
                    'S' | 's' => alt![ctrl s],
                    'T' | 't' => alt![ctrl t],
                    'U' | 'u' => alt![ctrl u],
                    'V' | 'v' => alt![ctrl v],
                    'W' | 'w' => alt![ctrl w],
                    'X' | 'x' => alt![ctrl x],
                    'Y' | 'y' => alt![ctrl y],
                    'Z' | 'z' => alt![ctrl z],
                    '4' => alt![ctrl 4],
                    '5' => alt![ctrl 5],
                    '6' => alt![ctrl 6],
                    '7' => alt![ctrl 7],
                    _ => None::<!>?,
                }},
            _ => None::<!>?,
        })
    }

    pub fn key(self) -> Option<Key> {
        match self {
            KeyOrChar::Key(key) => Some(key),
            KeyOrChar::Char(_) => None,
        }
    }

    pub fn char(self) -> Option<char> {
        match self {
            KeyOrChar::Key(key) => key.char(),
            KeyOrChar::Char(char) => Some(char),
        }
    }

    pub fn alt_char(self) -> Option<char> {
        match self {
            KeyOrChar::Key(key) => key.alt_char(),
            KeyOrChar::Char(_) => None,
        }
    }
}

impl Key {
    pub fn from_key_event(event: KeyEvent) -> Option<Self> {
        let or_char = KeyOrChar::from_key_event(event);
        match or_char? {
            KeyOrChar::Key(key) => Some(key),
            KeyOrChar::Char(_) => None,
        }
    }

    pub fn from_mouse_event(event: MouseEvent) -> Option<Self> {
        Some(match event.kind {
            MouseEventKind::ScrollDown => Key::ScrollDown,
            MouseEventKind::ScrollUp => Key::ScrollUp,
            MouseEventKind::ScrollLeft => Key::ScrollLeft,
            MouseEventKind::ScrollRight => Key::ScrollRight,
            MouseEventKind::Down(MouseButton::Left) => if event.modifiers.contains(KeyModifiers::ALT) {Key::AltLeftClick} else {Key::LeftClick},
            MouseEventKind::Drag(MouseButton::Left) => if event.modifiers.contains(KeyModifiers::ALT) {Key::AltLeftDrag} else {Key::LeftDrag},
            _ => None::<!>?
        })
    }

    pub fn char(self) -> Option<char> {
        Some(match self {
            Key::BackTick => '`',
            Key::One => '1',
            Key::Two => '2',
            Key::Three => '3',
            Key::Four => '4',
            Key::Five => '5',
            Key::Six => '6',
            Key::Seven => '7',
            Key::Eight => '8',
            Key::Nine => '9',
            Key::Zero => '0',
            Key::Minus => '-',
            Key::Equal => '=',
            Key::Tab => '\t',
            Key::Q => 'q',
            Key::W => 'w',
            Key::E => 'e',
            Key::R => 'r',
            Key::T => 't',
            Key::Y => 'y',
            Key::U => 'u',
            Key::I => 'i',
            Key::O => 'o',
            Key::P => 'p',
            Key::LeftBracket => '[',
            Key::RightBracket => ']',
            Key::Backslash => '\\',
            Key::A => 'a',
            Key::S => 's',
            Key::D => 'd',
            Key::F => 'f',
            Key::G => 'g',
            Key::H => 'h',
            Key::J => 'j',
            Key::K => 'k',
            Key::L => 'l',
            Key::Semicolon => ';',
            Key::Quote => '\'',
            Key::Return => '\n',
            Key::Z => 'z',
            Key::X => 'x',
            Key::C => 'c',
            Key::V => 'v',
            Key::B => 'b',
            Key::N => 'n',
            Key::M => 'm',
            Key::Comma => ',',
            Key::Dot => '.',
            Key::Slash => '/',
            Key::Space => ' ',
            Key::Squiggle => '~',
            Key::Bang => '!',
            Key::At => '@',
            Key::Hash => '#',
            Key::Dollar => '$',
            Key::Percent => '%',
            Key::Caret => '^',
            Key::Ampersand => '&',
            Key::Star => '*',
            Key::LeftParen => '(',
            Key::RightParen => ')',
            Key::Underscore => '_',
            Key::Plus => '+',
            Key::UpperQ => 'Q',
            Key::UpperW => 'W',
            Key::UpperE => 'E',
            Key::UpperR => 'R',
            Key::UpperT => 'T',
            Key::UpperY => 'Y',
            Key::UpperU => 'U',
            Key::UpperI => 'I',
            Key::UpperO => 'O',
            Key::UpperP => 'P',
            Key::LeftBrace => '{',
            Key::RightBrace => '}',
            Key::Bar => '|',
            Key::UpperA => 'A',
            Key::UpperS => 'S',
            Key::UpperD => 'D',
            Key::UpperF => 'F',
            Key::UpperG => 'G',
            Key::UpperH => 'H',
            Key::UpperJ => 'J',
            Key::UpperK => 'K',
            Key::UpperL => 'L',
            Key::Colon => ':',
            Key::DoubleQuote => '"',
            Key::UpperZ => 'Z',
            Key::UpperX => 'X',
            Key::UpperC => 'C',
            Key::UpperV => 'V',
            Key::UpperB => 'B',
            Key::UpperN => 'N',
            Key::UpperM => 'M',
            Key::LessThan => '<',
            Key::GreaterThan => '>',
            Key::Question => '?',
            _ => None::<!>?
        })
    }
    
    pub fn alt_char(self) -> Option<char> {
        Some(match self {
            Key::AltBackTick => '`',
            Key::AltOne => '1',
            Key::AltTwo => '2',
            Key::AltThree => '3',
            Key::AltFour => '4',
            Key::AltFive => '5',
            Key::AltSix => '6',
            Key::AltSeven => '7',
            Key::AltEight => '8',
            Key::AltNine => '9',
            Key::AltZero => '0',
            Key::AltMinus => '-',
            Key::AltEqual => '=',
            Key::AltTab => '\t',
            Key::AltQ => 'q',
            Key::AltW => 'w',
            Key::AltE => 'e',
            Key::AltR => 'r',
            Key::AltT => 't',
            Key::AltY => 'y',
            Key::AltU => 'u',
            Key::AltI => 'i',
            Key::AltO => 'o',
            Key::AltP => 'p',
            Key::AltLeftBracket => '[',
            Key::AltRightBracket => ']',
            Key::AltBackslash => '\\',
            Key::AltA => 'a',
            Key::AltS => 's',
            Key::AltD => 'd',
            Key::AltF => 'f',
            Key::AltG => 'g',
            Key::AltH => 'h',
            Key::AltJ => 'j',
            Key::AltK => 'k',
            Key::AltL => 'l',
            Key::AltSemicolon => ';',
            Key::AltQuote => '\'',
            Key::AltReturn => '\n',
            Key::AltZ => 'z',
            Key::AltX => 'x',
            Key::AltC => 'c',
            Key::AltV => 'v',
            Key::AltB => 'b',
            Key::AltN => 'n',
            Key::AltM => 'm',
            Key::AltComma => ',',
            Key::AltDot => '.',
            Key::AltSlash => '/',
            Key::AltSpace => ' ',
            Key::AltSquiggle => '~',
            Key::AltBang => '!',
            Key::AltAt => '@',
            Key::AltHash => '#',
            Key::AltDollar => '$',
            Key::AltPercent => '%',
            Key::AltCaret => '^',
            Key::AltAmpersand => '&',
            Key::AltStar => '*',
            Key::AltLeftParen => '(',
            Key::AltRightParen => ')',
            Key::AltUnderscore => '_',
            Key::AltPlus => '+',
            Key::AltUpperQ => 'Q',
            Key::AltUpperW => 'W',
            Key::AltUpperE => 'E',
            Key::AltUpperR => 'R',
            Key::AltUpperT => 'T',
            Key::AltUpperY => 'Y',
            Key::AltUpperU => 'U',
            Key::AltUpperI => 'I',
            Key::AltUpperO => 'O',
            Key::AltUpperP => 'P',
            Key::AltLeftBrace => '{',
            Key::AltRightBrace => '}',
            Key::AltBar => '|',
            Key::AltUpperA => 'A',
            Key::AltUpperS => 'S',
            Key::AltUpperD => 'D',
            Key::AltUpperF => 'F',
            Key::AltUpperG => 'G',
            Key::AltUpperH => 'H',
            Key::AltUpperJ => 'J',
            Key::AltUpperK => 'K',
            Key::AltUpperL => 'L',
            Key::AltColon => ':',
            Key::AltDoubleQuote => '"',
            Key::AltUpperZ => 'Z',
            Key::AltUpperX => 'X',
            Key::AltUpperC => 'C',
            Key::AltUpperV => 'V',
            Key::AltUpperB => 'B',
            Key::AltUpperN => 'N',
            Key::AltUpperM => 'M',
            Key::AltLessThan => '<',
            Key::AltGreaterThan => '>',
            Key::AltQuestion => '?',
            _ => None::<!>?
        })
    }
}

pub macro key {
    (esc) => {$crate::key::Key::Escape},
    (f1) => {$crate::key::Key::F1},
    (f2) => {$crate::key::Key::F2},
    (f3) => {$crate::key::Key::F3},
    (f4) => {$crate::key::Key::F4},
    (f5) => {$crate::key::Key::F5},
    (f6) => {$crate::key::Key::F6},
    (f7) => {$crate::key::Key::F7},
    (f8) => {$crate::key::Key::F8},
    (f9) => {$crate::key::Key::F9},
    (f10) => {$crate::key::Key::F10},
    (f11) => {$crate::key::Key::F11},
    (f12) => {$crate::key::Key::F12},
    ('`') => {$crate::key::Key::BackTick},
    (1) => {$crate::key::Key::One},
    (2) => {$crate::key::Key::Two},
    (3) => {$crate::key::Key::Three},
    (4) => {$crate::key::Key::Four},
    (5) => {$crate::key::Key::Five},
    (6) => {$crate::key::Key::Six},
    (7) => {$crate::key::Key::Seven},
    (8) => {$crate::key::Key::Eight},
    (9) => {$crate::key::Key::Nine},
    (0) => {$crate::key::Key::Zero},
    (-) => {$crate::key::Key::Minus},
    (=) => {$crate::key::Key::Equal},
    (backspace) => {$crate::key::Key::Backspace},
    (tab) => {$crate::key::Key::Tab},
    (q) => {$crate::key::Key::Q},
    (w) => {$crate::key::Key::W},
    (e) => {$crate::key::Key::E},
    (r) => {$crate::key::Key::R},
    (t) => {$crate::key::Key::T},
    (y) => {$crate::key::Key::Y},
    (u) => {$crate::key::Key::U},
    (i) => {$crate::key::Key::I},
    (o) => {$crate::key::Key::O},
    (p) => {$crate::key::Key::P},
    ('[') => {$crate::key::Key::LeftBracket},
    (']') => {$crate::key::Key::RightBracket},
    (backslash) => {$crate::key::Key::Backslash},
    (a) => {$crate::key::Key::A},
    (s) => {$crate::key::Key::S},
    (d) => {$crate::key::Key::D},
    (f) => {$crate::key::Key::F},
    (g) => {$crate::key::Key::G},
    (h) => {$crate::key::Key::H},
    (j) => {$crate::key::Key::J},
    (k) => {$crate::key::Key::K},
    (l) => {$crate::key::Key::L},
    (;) => {$crate::key::Key::Semicolon},
    ("'") => {$crate::key::Key::Quote},
    (return) => {$crate::key::Key::Return},
    (z) => {$crate::key::Key::Z},
    (x) => {$crate::key::Key::X},
    (c) => {$crate::key::Key::C},
    (v) => {$crate::key::Key::V},
    (b) => {$crate::key::Key::B},
    (n) => {$crate::key::Key::N},
    (m) => {$crate::key::Key::M},
    (,) => {$crate::key::Key::Comma},
    (.) => {$crate::key::Key::Dot},
    (/) => {$crate::key::Key::Slash},
    ( ) => {$crate::key::Key::Space},

    (~) => {$crate::key::Key::Squiggle},
    (!) => {$crate::key::Key::Bang},
    (@) => {$crate::key::Key::At},
    (#) => {$crate::key::Key::Hash},
    ($) => {$crate::key::Key::Dollar},
    (%) => {$crate::key::Key::Percent},
    (^) => {$crate::key::Key::Caret},
    (&) => {$crate::key::Key::Ampersand},
    (*) => {$crate::key::Key::Star},
    ('(') => {$crate::key::Key::LeftParen},
    (')') => {$crate::key::Key::RightParen},
    (_) => {$crate::key::Key::Underscore},
    (+) => {$crate::key::Key::Plus},
    (back tab) => {$crate::key::Key::BackTab},
    (Q) => {$crate::key::Key::UpperQ},
    (W) => {$crate::key::Key::UpperW},
    (E) => {$crate::key::Key::UpperE},
    (R) => {$crate::key::Key::UpperR},
    (T) => {$crate::key::Key::UpperT},
    (Y) => {$crate::key::Key::UpperY},
    (U) => {$crate::key::Key::UpperU},
    (I) => {$crate::key::Key::UpperI},
    (O) => {$crate::key::Key::UpperO},
    (P) => {$crate::key::Key::UpperP},
    ('{') => {$crate::key::Key::LeftBrace},
    ('}') => {$crate::key::Key::RightBrace},
    (|) => {$crate::key::Key::Bar},
    (A) => {$crate::key::Key::UpperA},
    (S) => {$crate::key::Key::UpperS},
    (D) => {$crate::key::Key::UpperD},
    (F) => {$crate::key::Key::UpperF},
    (G) => {$crate::key::Key::UpperG},
    (H) => {$crate::key::Key::UpperH},
    (J) => {$crate::key::Key::UpperJ},
    (K) => {$crate::key::Key::UpperK},
    (L) => {$crate::key::Key::UpperL},
    (:) => {$crate::key::Key::Colon},
    ('"') => {$crate::key::Key::DoubleQuote},
    (Z) => {$crate::key::Key::UpperZ},
    (X) => {$crate::key::Key::UpperX},
    (C) => {$crate::key::Key::UpperC},
    (V) => {$crate::key::Key::UpperV},
    (B) => {$crate::key::Key::UpperB},
    (N) => {$crate::key::Key::UpperN},
    (M) => {$crate::key::Key::UpperM},
    (<) => {$crate::key::Key::LessThan},
    (>) => {$crate::key::Key::GreaterThan},
    (?) => {$crate::key::Key::Question},

    (ctrl a) => {$crate::key::Key::CtrlA},
    (ctrl b) => {$crate::key::Key::CtrlB},
    (ctrl c) => {$crate::key::Key::CtrlC},
    (ctrl d) => {$crate::key::Key::CtrlD},
    (ctrl e) => {$crate::key::Key::CtrlE},
    (ctrl f) => {$crate::key::Key::CtrlF},
    (ctrl g) => {$crate::key::Key::CtrlG},
    (ctrl h) => {$crate::key::Key::CtrlH},
    (ctrl j) => {$crate::key::Key::CtrlJ},
    (ctrl k) => {$crate::key::Key::CtrlK},
    (ctrl l) => {$crate::key::Key::CtrlL},
    (ctrl n) => {$crate::key::Key::CtrlN},
    (ctrl o) => {$crate::key::Key::CtrlO},
    (ctrl p) => {$crate::key::Key::CtrlP},
    (ctrl q) => {$crate::key::Key::CtrlQ},
    (ctrl r) => {$crate::key::Key::CtrlR},
    (ctrl s) => {$crate::key::Key::CtrlS},
    (ctrl t) => {$crate::key::Key::CtrlT},
    (ctrl u) => {$crate::key::Key::CtrlU},
    (ctrl v) => {$crate::key::Key::CtrlV},
    (ctrl w) => {$crate::key::Key::CtrlW},
    (ctrl x) => {$crate::key::Key::CtrlX},
    (ctrl y) => {$crate::key::Key::CtrlY},
    (ctrl z) => {$crate::key::Key::CtrlZ},
    (ctrl 4) => {$crate::key::Key::Ctrl4},
    (ctrl 5) => {$crate::key::Key::Ctrl5},
    (ctrl 6) => {$crate::key::Key::Ctrl6},
    (ctrl 7) => {$crate::key::Key::Ctrl7},

    (alt esc) => {$crate::key::Key::AltEscape},
    (alt f1) => {$crate::key::Key::AltF1},
    (alt f2) => {$crate::key::Key::AltF2},
    (alt f3) => {$crate::key::Key::AltF3},
    (alt f4) => {$crate::key::Key::AltF4},
    (alt f5) => {$crate::key::Key::AltF5},
    (alt f6) => {$crate::key::Key::AltF6},
    (alt f7) => {$crate::key::Key::AltF7},
    (alt f8) => {$crate::key::Key::AltF8},
    (alt f9) => {$crate::key::Key::AltF9},
    (alt f10) => {$crate::key::Key::AltF10},
    (alt f11) => {$crate::key::Key::AltF11},
    (alt f12) => {$crate::key::Key::AltF12},
    (alt '`') => {$crate::key::Key::AltBackTick},
    (alt 1) => {$crate::key::Key::AltOne},
    (alt 2) => {$crate::key::Key::AltTwo},
    (alt 3) => {$crate::key::Key::AltThree},
    (alt 4) => {$crate::key::Key::AltFour},
    (alt 5) => {$crate::key::Key::AltFive},
    (alt 6) => {$crate::key::Key::AltSix},
    (alt 7) => {$crate::key::Key::AltSeven},
    (alt 8) => {$crate::key::Key::AltEight},
    (alt 9) => {$crate::key::Key::AltNine},
    (alt 0) => {$crate::key::Key::AltZero},
    (alt -) => {$crate::key::Key::AltMinus},
    (alt =) => {$crate::key::Key::AltEqual},
    (alt backspace) => {$crate::key::Key::AltBackspace},
    (alt tab) => {$crate::key::Key::AltTab},
    (alt q) => {$crate::key::Key::AltQ},
    (alt w) => {$crate::key::Key::AltW},
    (alt e) => {$crate::key::Key::AltE},
    (alt r) => {$crate::key::Key::AltR},
    (alt t) => {$crate::key::Key::AltT},
    (alt y) => {$crate::key::Key::AltY},
    (alt u) => {$crate::key::Key::AltU},
    (alt i) => {$crate::key::Key::AltI},
    (alt o) => {$crate::key::Key::AltO},
    (alt p) => {$crate::key::Key::AltP},
    (alt '[') => {$crate::key::Key::AltLeftBracket},
    (alt ']') => {$crate::key::Key::AltRightBracket},
    (alt backslash) => {$crate::key::Key::AltBackslash},
    (alt a) => {$crate::key::Key::AltA},
    (alt s) => {$crate::key::Key::AltS},
    (alt d) => {$crate::key::Key::AltD},
    (alt f) => {$crate::key::Key::AltF},
    (alt g) => {$crate::key::Key::AltG},
    (alt h) => {$crate::key::Key::AltH},
    (alt j) => {$crate::key::Key::AltJ},
    (alt k) => {$crate::key::Key::AltK},
    (alt l) => {$crate::key::Key::AltL},
    (alt ;) => {$crate::key::Key::AltSemicolon},
    (alt "'") => {$crate::key::Key::AltQuote},
    (alt return) => {$crate::key::Key::AltReturn},
    (alt z) => {$crate::key::Key::AltZ},
    (alt x) => {$crate::key::Key::AltX},
    (alt c) => {$crate::key::Key::AltC},
    (alt v) => {$crate::key::Key::AltV},
    (alt b) => {$crate::key::Key::AltB},
    (alt n) => {$crate::key::Key::AltN},
    (alt m) => {$crate::key::Key::AltM},
    (alt ,) => {$crate::key::Key::AltComma},
    (alt .) => {$crate::key::Key::AltDot},
    (alt /) => {$crate::key::Key::AltSlash},
    (alt  ) => {$crate::key::Key::AltSpace},

    (alt ~) => {$crate::key::Key::AltSquiggle},
    (alt !) => {$crate::key::Key::AltBang},
    (alt @) => {$crate::key::Key::AltAt},
    (alt #) => {$crate::key::Key::AltHash},
    (alt $) => {$crate::key::Key::AltDollar},
    (alt %) => {$crate::key::Key::AltPercent},
    (alt ^) => {$crate::key::Key::AltCaret},
    (alt &) => {$crate::key::Key::AltAmpersand},
    (alt *) => {$crate::key::Key::AltStar},
    (alt '(') => {$crate::key::Key::AltLeftParen},
    (alt ')') => {$crate::key::Key::AltRightParen},
    (alt _) => {$crate::key::Key::AltUnderscore},
    (alt +) => {$crate::key::Key::AltPlus},
    (alt back tab) => {$crate::key::Key::AltBackTab},
    (alt Q) => {$crate::key::Key::AltUpperQ},
    (alt W) => {$crate::key::Key::AltUpperW},
    (alt E) => {$crate::key::Key::AltUpperE},
    (alt R) => {$crate::key::Key::AltUpperR},
    (alt T) => {$crate::key::Key::AltUpperT},
    (alt Y) => {$crate::key::Key::AltUpperY},
    (alt U) => {$crate::key::Key::AltUpperU},
    (alt I) => {$crate::key::Key::AltUpperI},
    (alt O) => {$crate::key::Key::AltUpperO},
    (alt P) => {$crate::key::Key::AltUpperP},
    (alt '{') => {$crate::key::Key::AltLeftBrace},
    (alt '}') => {$crate::key::Key::AltRightBrace},
    (alt |) => {$crate::key::Key::AltBar},
    (alt A) => {$crate::key::Key::AltUpperA},
    (alt S) => {$crate::key::Key::AltUpperS},
    (alt D) => {$crate::key::Key::AltUpperD},
    (alt F) => {$crate::key::Key::AltUpperF},
    (alt G) => {$crate::key::Key::AltUpperG},
    (alt H) => {$crate::key::Key::AltUpperH},
    (alt J) => {$crate::key::Key::AltUpperJ},
    (alt K) => {$crate::key::Key::AltUpperK},
    (alt L) => {$crate::key::Key::AltUpperL},
    (alt :) => {$crate::key::Key::AltColon},
    (alt '"') => {$crate::key::Key::AltDoubleQuote},
    (alt Z) => {$crate::key::Key::AltUpperZ},
    (alt X) => {$crate::key::Key::AltUpperX},
    (alt C) => {$crate::key::Key::AltUpperC},
    (alt V) => {$crate::key::Key::AltUpperV},
    (alt B) => {$crate::key::Key::AltUpperB},
    (alt N) => {$crate::key::Key::AltUpperN},
    (alt M) => {$crate::key::Key::AltUpperM},
    (alt <) => {$crate::key::Key::AltLessThan},
    (alt >) => {$crate::key::Key::AltGreaterThan},
    (alt ?) => {$crate::key::Key::AltQuestion},

    (ctrl alt a) => {$crate::key::Key::CtrlAltA},
    (ctrl alt b) => {$crate::key::Key::CtrlAltB},
    (ctrl alt c) => {$crate::key::Key::CtrlAltC},
    (ctrl alt d) => {$crate::key::Key::CtrlAltD},
    (ctrl alt e) => {$crate::key::Key::CtrlAltE},
    (ctrl alt f) => {$crate::key::Key::CtrlAltF},
    (ctrl alt g) => {$crate::key::Key::CtrlAltG},
    (ctrl alt h) => {$crate::key::Key::CtrlAltH},
    (ctrl alt j) => {$crate::key::Key::CtrlAltJ},
    (ctrl alt k) => {$crate::key::Key::CtrlAltK},
    (ctrl alt l) => {$crate::key::Key::CtrlAltL},
    (ctrl alt n) => {$crate::key::Key::CtrlAltN},
    (ctrl alt o) => {$crate::key::Key::CtrlAltO},
    (ctrl alt p) => {$crate::key::Key::CtrlAltP},
    (ctrl alt q) => {$crate::key::Key::CtrlAltQ},
    (ctrl alt r) => {$crate::key::Key::CtrlAltR},
    (ctrl alt s) => {$crate::key::Key::CtrlAltS},
    (ctrl alt t) => {$crate::key::Key::CtrlAltT},
    (ctrl alt u) => {$crate::key::Key::CtrlAltU},
    (ctrl alt v) => {$crate::key::Key::CtrlAltV},
    (ctrl alt w) => {$crate::key::Key::CtrlAltW},
    (ctrl alt x) => {$crate::key::Key::CtrlAltX},
    (ctrl alt y) => {$crate::key::Key::CtrlAltY},
    (ctrl alt z) => {$crate::key::Key::CtrlAltZ},
    (ctrl alt 4) => {$crate::key::Key::CtrlAlt4},
    (ctrl alt 5) => {$crate::key::Key::CtrlAlt5},
    (ctrl alt 6) => {$crate::key::Key::CtrlAlt6},
    (ctrl alt 7) => {$crate::key::Key::CtrlAlt7},

    (scroll up) => {$crate::key::Key::ScrollUp},
    (scroll down) => {$crate::key::Key::ScrollDown},
    (scroll left) => {$crate::key::Key::ScrollLeft},
    (scroll right) => {$crate::key::Key::ScrollRight},

    (left click) => {$crate::key::Key::LeftClick},
    (left drag) => {$crate::key::Key::LeftDrag},
    (alt left click) => {$crate::key::Key::AltLeftClick},
    (alt left drag) => {$crate::key::Key::AltLeftDrag},
}
